#ifndef _Z_BUILD_CONFIG_H_
#define _Z_BUILD_CONFIG_H_

#define Z_IOPOLL_HAS_EPOLL
#define Z_SOCKET_HAS_UNIX
#define Z_IOPOLL_HAS_SELECT
#define Z_STRING_HAS_MEMSET
#define Z_STRING_HAS_MEMCMP
#define Z_STRING_HAS_MEMMOVE
#define Z_STRING_HAS_MEMCPY
#define Z_STRING_HAS_MEMCHR
#define Z_PTHREAD_HAS_COND
#define Z_PTHREAD_HAS_SPIN
#define Z_PTHREAD_HAS_THREAD
#define Z_PTHREAD_HAS_RWLOCK
#define Z_PTHREAD_HAS_MUTEX

#endif /* !_Z_BUILD_CONFIG_H_ */
